targets:
  $default:
    builders:
      json_serializable:
        options:
          # JSON のパースに失敗した際に CheckedFromJsonException をスローさせる。
          checked: true
          # スネークケースに変換する。
          # field_rename: snake
