name: preflop_trainer
description: "ポーカーのプリフロップハンドレンジを学習するためのアプリケーションです。"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  intl: any
  json_annotation: ^4.9.0
  logger: ^2.5.0
  package_info_plus: ^8.3.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  url_strategy: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.10.0
  flutter_svg: ^2.0.17
  flutter_test:
    sdk: flutter
  # freezed: ^3.0.4
  freezed: ^2.5.7
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  riverpod_generator: ^2.6.3
  riverpod_lint:
    
flutter_gen:
  output: lib/ui/style/gen/
  integrations:
    flutter_svg: true
  assets:
    outputs:
      class_name: Assets

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/fonts/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-SemiBold.ttf
          weight: 600
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
