name: preflop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  intl: any
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  url_strategy: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.10.0
  flutter_svg: ^2.0.17
  flutter_test:
    sdk: flutter
  # freezed: ^3.0.4
  freezed: ^2.5.7
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  riverpod_generator: ^2.6.3
  riverpod_lint:
    
flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
  assets:
    outputs:
      class_name: Assets

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: lib/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: lib/fonts/NotoSansJP-SemiBold.ttf
          weight: 600
